### ISSUE TITLE
Use compose environment variable injection instead of env file

### ISSUE THREAD

**Issue by JamesOrson** [ExoKomodo/Daybreak#108]
Instead of defining an env file, directly inject the environment variables like so
```yaml
services:
  build:
    environment: CC_COMPILER=${CC_COMPILER}
```
This allows the environment to define the variables more readily and allows the compose file to serve as documentation
